version: "3.9"

services:
  worklog-analytics:
    build: .
    container_name: worklog-analytics-container
    ports:
      - "8003:8003"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - trello-dashboard_trello_auth_data:/data:ro
    restart: unless-stopped

volumes:
  trello-dashboard_trello_auth_data:
    external: true
